preprocess:
  sampling_rate:  &samplingrate  22050
  signal_length:  &signallength  88200
  block_size:     &blocksize 245
  conf_threshold: 0.85
  out_dir: ./preprocessed/
  data_location:  /home/teaonly/dataset/CINSTR/dizi
  extension: "wav"

model:
  sampling_rate: *samplingrate
  block_size: *blocksize
 
  input_hop:  4
  input_length: &inputlength 64
  hidden_size:  256
  
  FM_config: [12.0, 3.0, 1.0,  8.5, 3.2, 1.0,  2.0, 1.0, 1.0]
  FM_amp:  3.0
  noise_bands: 65
  reverb_length: 1024

train:
  scales:   [ 4096,   2048,  1024,  512,   256,  128]
  weights:  [ 1.0,    1.0,   1.0,   1.0,   1.0,  1.0]
  overlap:  0.75
